#!/bin/bash
# Description: Combines all individual Helixer GFF prediction files into a single GFF3 file.

# --- USER-DEFINED VARIABLES ---
GENOTYPE="GDB_136"

# --- FILE PATHS ---
# Directory where all the individual GFF files are located
GFF_DIR="${GENOTYPE}" 
# The final combined GFF output file
OUTPUT_GFF="${GENOTYPE}/${GENOTYPE}.helixer.combined.gff3" 
# Log file (for tracking)
LOG_FILE="logs/${GENOTYPE}.helixer_combine.log"

# --- SETUP AND INPUT CHECK ---
mkdir -p logs

# Find all GFF files in the genotype directory that match the pattern
# The pattern ensures we only pick up the Helixer output files (e.g., GDB_136.chr1A.helixer.gff)
INPUT_GFFS=$(find "${GFF_DIR}" -maxdepth 1 -name "${GENOTYPE}.*.helixer.gff" -type f)

if [ -z "$INPUT_GFFS" ]; then
    echo "ERROR: No individual Helixer GFF files found in ${GFF_DIR}/ to combine." | tee "$LOG_FILE"
    echo "Please ensure the 'run_helixer' step has completed successfully for all chunks." | tee -a "$LOG_FILE"
    exit 1
fi

TOTAL_FILES=$(echo "$INPUT_GFFS" | wc -l)
echo "--- Starting GFF combination for ${GENOTYPE} ---" | tee "$LOG_FILE"
echo "Found ${TOTAL_FILES} individual Helixer GFF files to combine." | tee -a "$LOG_FILE"

# --- CORE EXECUTION ---

# The original Snakemake shell command: "cat {input.gffs} > {output.gff}"
# We use the list generated by 'find' and pipe it into the final output file.
# Note: 'xargs' is used to pass the file list to 'cat' efficiently.

echo "$INPUT_GFFS" | xargs cat > "${OUTPUT_GFF}" 2>> "$LOG_FILE"

EXIT_CODE=$?

# --- FINAL REPORT ---
if [ "$EXIT_CODE" -eq 0 ]; then
    echo "--- SUCCESS: Helixer GFFs combined successfully. ---" | tee -a "$LOG_FILE"
    echo "Final file: ${OUTPUT_GFF}" | tee -a "$LOG_FILE"
else
    echo "--- ERROR: GFF combination failed (Exit Code: $EXIT_CODE). ---" | tee -a "$LOG_FILE"
fi

exit $EXIT_CODE
